apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
data:
  DB_USER: {{ .Values.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}